export const CATEGORIES = [
  "Pastoraat",
  "Mentoraat",
  "Diaconie",
  "Kerkenraad",
  "Commissie van beheer",
  "Jeugd",
  "Muziek & eredienst",
  "Beamteam",
  "Geluidsteam",
  "Zondagsbrief",
  "Bijbelleesrooster",
  "Koster",
  "Techniek",
  "Communicatie",
  "Administratie",
  "Financiën",
  "Onderwijs",
  "Praktisch",
  "Overig",
];

export const CATEGORY_ICONS: Record<string, string> = {
  "Pastoraat":            "🤝",
  "Mentoraat":            "🌱",
  "Diaconie":             "💛",
  "Kerkenraad":           "🏛️",
  "Commissie van beheer": "🔑",
  "Jeugd":                "🧒",
  "Muziek & eredienst":   "🎵",
  "Beamteam":             "📽️",
  "Geluidsteam":          "🎚️",
  "Zondagsbrief":         "📋",
  "Bijbelleesrooster":    "📖",
  "Koster":               "⛪",
  "Techniek":             "🔧",
  "Communicatie":         "📢",
  "Administratie":        "📂",
  "Financiën":            "💰",
  "Onderwijs":            "📚",
  "Praktisch":            "🛠️",
  "Overig":               "📌",
};
